version: "3.8"

services:
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: "true"
      TYPE: "FORGE"
      VERSION: "1.19.2"
      FORGE_VERISON: "43.2.0"
    ports:
      - "25565:25565"
    volumes:
      - ./data:/data
      - ./mods:/mods
    stdin_open: true
    tty: true
    restart: unless-stopped
volumes:
  - ./home/minecraft/minecraft-data:/data
  - ./home/minecraft/mods:/mods